version: '3.7'

services:
  kasm_alpine:
    image: kasmweb/alpine-321-desktop:1.17.0
    container_name: kasm_alpine
    restart: unless-stopped
    ports:
      - "6901:6901"  # Acesso externo ao VNC pelo navegador
    shm_size: 512m
    environment:
      - VNC_PW=umbrel
    networks:
      - app_net  # mesma rede usada por Umbrel apps

networks:
  app_net:
    external: true
    name: umbrel_app_net  # essa é a rede padrão dos apps do Umbrel
