version: '3.7'

services:
  kasm_alpine:
    image: kasmweb/alpine-321-desktop:1.17.0
    container_name: kasm_alpine
    restart: unless-stopped
    ports:
      - "6901:6901"
    shm_size: 512m
    environment:
      - VNC_PW=umbrel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kasm.rule=Host(`kasm.local`)"
      - "traefik.http.services.kasm.loadbalancer.server.port=6901"
